name: Clase1 - Java CI

on:
  push:
    branches: [ main ]
    paths:
      - 'clase1/java-app/**'  # Solo se activa con cambios en esta ruta
  pull_request:
    branches: [ main ]
    paths:
      - 'clase1/java-app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clase1/java-app  # Ejecuta comandos en esta carpeta
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
