name: Clase1 - .NET CI

on:
  push:
    branches: [ main ]
    paths:
      - 'clase1/dotnet-app/**'  # Solo cambios en esta carpeta
  pull_request:
    branches: [ main ]
    paths:
      - 'clase1/dotnet-app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clase1/dotnet-app  # Ruta del proyecto .NET
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal